### ISSUE TITLE
hope to provide further tutorials and sample data

### ISSUE THREAD

**Issue by jeannotes** [Cartucho/vision_blender#10]
hi, due to not familiar with blender, it is a little bit hard for me to understand this, can you provide a more concrete example and the relative data sample, thanks

**Comment by Cartucho** [comment]
@jeannotes good idea, I should do a tutorial, which parts do you find it harder to understand? How to install or how to use the add-on? or both?

**Comment by Cartucho** [comment]
Hello! I just added gifs in GitHub's README explaining how to install and generate the ground truth.
Let me know what you think

**Comment by jeannotes** [comment]
@Cartucho what is the input and output, if input is stanford bunny , it will render out some segmentation outputs?

**Comment by Cartucho** [comment]
Imagine you want to segment the Stanford bunny. You have to:

1. import the bunny into blender;
2. put the bunny in front of the camera;
3. install the add-on as explained in the README;
4. set the rendering engine to Cycles;
4. set the bunny object index to an integer !=0;
5. render an image
6. load the .npz file as shown in the examples.

If you have trouble in any of the steps let me know.
