### ISSUE TITLE
Having issues getting ground truth output

### ISSUE THREAD

**Issue by chunter18** [Cartucho/vision_blender#11]
Hi @Cartucho, thanks for creating this tool. Im having some difficulties getting the ground truth to appear for whatever reason, I was hoping you might be able to help.

Blender version: 2.83.4 (same issues in 2.9)
Addon installed and enabled: Yes
Vision Blender UI enabled: Yes
Vision Blender outputs selected: Depth, Normals, Seg Masks
Render Engine: Cycles (also tried evee just to see)

My scene is super simple, just a single object with a light an no camera motion. I can supply .blend files if needed, but I think the chances are high I just missed something obvious.

**Comment by chunter18** [comment]
Some follow up:
1. Does the add on only work when outputting data as images (I was using FFMPEG video, everything seems to work )
2. Do all combinations of output selections work? This I haven't tested, but just want to confirm - my successes have been when exporting everything.

Thanks again, this is really a fantastic tool!

**Comment by Cartucho** [comment]
Hi, thank you for letting me know.
A simple test you can do is to generate for the standard blender scene, before changing any setting.

The add-on was designed to generate the ground-truth when rendering images or animations. I haven't tried to see if it works when rendering videos directly.

I need to check but I think the issue may be with the data type (image output format). So far, I have tested on `.png` and `.jpg`. I will try with the other ones.

Which output do you want? Like here, what are you settings?
![image](https://user-images.githubusercontent.com/15831541/117146448-1f893d00-adac-11eb-9290-0ce75479b6ec.png)

**Comment by Cartucho** [comment]
Hi, I tried with the different image and video formats and it worked fine.

Could it be that the output was being written in the `/tmp/` folder?

**Comment by Cartucho** [comment]
@chunter18 also, there used to be a bug in a previous version that was creating issues with getting the ground truth. Maybe you can also try updating?

**Comment by chunter18** [comment]
My problem was just that I was outputting to FFMPEG video instead of as PNG or JPG - changing that fixed everything, it now works perfectly. I will go ahead and close this out.
