### ISSUE TITLE
Data not saving to the scene render filepath

### ISSUE THREAD

**Issue by nmarchuk** [Cartucho/vision_blender#13]
`Saved: C:\tmp\opt_flow\Image0001.exr
Saved: C:\Users\Nicholas Marchuk\Documents\Research\Summer\test_output\segmentation_masks\1_0001.tga
Saved: 'C:\Users\Nicholas Marchuk\Documents\Research\Summer\test_output\0001.png'
 Time: 00:03.30 (Saving: 00:00.06)

Saved: C:\tmp\opt_flow\Image0002.exr
Saved: C:\Users\Nicholas Marchuk\Documents\Research\Summer\test_output\segmentation_masks\1_0002.tga
Saved: 'C:\Users\Nicholas Marchuk\Documents\Research\Summer\test_output\0002.png'
 Time: 00:03.28 (Saving: 00:00.07))`

and so on...

The optical flow images are getting saved to my tmp directory. I think this may have to do with how Blender is launched? I have an installed instance of blender, not built from source.

When I print out `data.filepaths` in `read_data.py` I get `['segmentation_masks', 'intrinsic_mat', 'extrinsic_mat', 'normal_map', 'depth_map', 'object_pose_labels', 'object_pose_mats']` which for some reason does not contain optical flow data.

Typically i would launch blender from visual studio, and call os.getcwd() to get the correct place, but right now the VSC addon is broken.

Let me know if you have insight into why this happens. The people in the Blender discord are usually pretty good about this stuff if you have trouble.

**Comment by Cartucho** [comment]
Ok, let me have a look at the code. It has to do with some path.

**Comment by Cartucho** [comment]
I am not sure if this is it but I just committed a change, do you think you could give it a try?

**Comment by nmarchuk** [comment]
Unfortunately that didn't seem work for me. I have to go now but when I get back I'll try to see about making it work and report back. But good catch on the dirname thing cause that is useful (I needed it for my synth data stuff)

**Comment by Cartucho** [comment]
That path is set in here, if you run blender on the terminal you could print it out: https://github.com/Cartucho/vision_blender/blob/11f37653dae56c941b15d976fa5fe53844d49498/addon_ground_truth_generation.py#L312

**Comment by nmarchuk** [comment]
Hi, back at work today. The problem has to do with the optical flow node saving the base path. I had run the program once with the /tmp/ path, and since the optical flow node won't update after you populate it (checking is_linked) it was not able to 'fix' itself.

The only problem left is that the EXR and segmentation mask file representations seem to get saved (with an entry in the log file) and then as soon as the next one starts rendering they get deleted? And so at the end the opt_flow and segmentation_masks folders are empty.

**Comment by Cartucho** [comment]
Ohhhh that makes sense!
We should reset both the nodes for the `segmentation masks` and for the `optical flow` every time before rendering.
I will make that modification to the code.

Regarding the files being deleted, that is currently normal behaviour. I am hoping for this [bug](https://developer.blender.org/T54314) to be solved so that I don't have to write any data to the disk.

**Comment by Cartucho** [comment]
The other option to tackle that bug would be to render each frame multiple times, but that would be too slow in my opinion.

**Comment by Cartucho** [comment]
Done, should work fine now! Basically, it will set up the nodes again every time a user presses render, therefore it won't have an issue with the user changing the path, or even if the user changed the nodes.

**Comment by nmarchuk** [comment]
Thanks for all your help!
