### ISSUE TITLE
The addon does not output .npz files when rendering

### ISSUE THREAD

**Issue by tahasamavati** [Cartucho/vision_blender#17]
Hi, Thanks for your work. it really is a great job!

I previously used the module to render a short animation and it successfully generated the .npz files. After some time I reopened the project to re-render the scene with some modifications. But when rendering, no .npz files are generated. I double-checked and the addon was enabled with all the required options checked. Blender just renders the images and nothing more. I also tried to re-install it but it didn't work. Could you please help me with this issue? 

I am using the latest clone of the repo and blender version 2.93.1

Here is my code:

import bpy
import random
import os
import mathutils
import numpy as np

scene = bpy.data.scenes['Scene']
scene.frame_end= 1
camera_object = bpy.data.objects['Camera']

for i in range(0,10):
.....bpy.context.scene.vision_blender.bool_save_gt_data = True
.....camera_object.location = (i+10, 0, 20)
.....bpy.context.scene.render.filepath = "C:/Users/Taha/Desktop/output/"+str(i+1)
.....bpy.ops.render.render(write_still=True, animation=True)

**Comment by Cartucho** [comment]
Hello, could you please make sure that you are using the latest version of this code and give it a try?

I think this may be due to a previous bug that has been fixed [in this commit](https://github.com/Cartucho/vision_blender/commit/b476946b024e62cc4f5e5503ca82035d136793d1/).

**Comment by Cartucho** [comment]
@tahasamavati also in your code, why are you setting `scene.frame_end = 1` if you later try to render multiple images?

**Comment by tahasamavati** [comment]
> @tahasamavati also in your code, why are you setting `scene.frame_end = 1` if you later try to render multiple images?

Yeah right. but this was the only way I could get the .npz ground-truth files (by rendering in animation mode in the previous commit). I tested this script with the latest commit and it doesn't work for me at all. I read your code and I think there is a problem in file naming causing mismatch or something like this

Could you please try my code on a simple project (i.e. Cube) to see if you have the same problem?  Thanks.

**Comment by tahasamavati** [comment]
I intend to render still images (not animation) by placing the camera in some desired locations. But in the previous commit, it did not output .npz files. As the addon generated gt files in animation mode. I set the scene.frame_end to 1. BTW I know that there must be some better ways to achieve this.

**Comment by Cartucho** [comment]
Apologies, I made a silly mistake, and it still passed the tests because I always testes will all the things active.
I will add more tests to avoid this in the future.

Also, the addon generates one `.npz` file per each `animation_frame`, so in your case, it would only generate a single `.npz` file. Could you please try the following code?

```
import bpy
import random
import os
import mathutils
import numpy as np

scene = bpy.data.scenes['Scene']
camera_object = bpy.data.objects['Camera']
out_folder = "C:/Users/Taha/Desktop/output/"

bpy.context.scene.vision_blender.bool_save_gt_data = True
scene.frame_end = 10
for frame_n in range(1, 11): # 11 is exclusive
    scene.frame_set(frame_n)
    camera_object.location = (frame_n+10, 0, 20)
    scene.render.filepath = os.path.join(out_folder, '{0:04}.png'.format(frame_n))
    bpy.ops.render.render(write_still=True)
```

**Comment by tahasamavati** [comment]
Works like charm. Thanks!
