### ISSUE TITLE
key "Render Layers" not found'

### ISSUE THREAD

**Issue by blukaz** [Cartucho/vision_blender#19]
Hi, I just followed your installation guide and got stuck at the rendering step. Here is the error which I get in the System Console:

```
File "C:\Users\barel\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\addon_ground_truth_generation.py", line 373, in load_handler_render_init
    rl = scene.node_tree.nodes["Render Layers"] # I assumed there is always a Render Layers
KeyError: 'bpy_prop_collection[key]: key "Render Layers" not found'
```

Do you have any idea what the issue might be?
Thanks!

**Comment by Cartucho** [comment]
I can see from the message that you are using version 2.93, I haven't tried that version yet. What the message is saying is that you do not have a "Render Layers".

In the previous version we get the following if you click the `Compositing` tab:

![image](https://user-images.githubusercontent.com/15831541/135079335-6af87016-1fec-4ddb-a08f-a25f521e4bb6.png)

Can you show me what do you have?

Also if you then click on `Item` on the right you should be able to find the correct name:

![image](https://user-images.githubusercontent.com/15831541/135079474-7aabdca4-0898-4ef2-979d-a9154443345f.png)

Let me know if they changed the default name in the newer version.

**Comment by blukaz** [comment]
Thank you for your quick reply. It somehow appeared that I didn't have the nodes in the Compositing tab.
BTW, the name is still the same.

Actually, I'm facing a different problem. Namely, the images get saved in the specifed output folder but they get deleted once I try to do something with them (open, copy, cut, etc.). Is it a common issue?

**Comment by Cartucho** [comment]
which images? the RGB rendering? or the .npz files?

**Comment by blukaz** [comment]
![files_disappear](https://user-images.githubusercontent.com/19351525/135233500-9547ebb7-c2d8-480b-bdb8-d0663cb20a9c.png)
they appear for a second and then get deleted...

**Comment by Cartucho** [comment]
Those are temporary files, so they are purposely deleted, you should process the data from the `.npz` files as explained in the [README](https://github.com/Cartucho/vision_blender/blob/master/README.md#how-to-read-the-data-after-generating-it).

Maybe I should delete the `tmp_vision_blender` folder at the end of rendering to avoid this confusion, right? What do you think?

Can you find the `.npz` files in your folder?
