### ISSUE TITLE
access to virtual surgical instruments

### ISSUE THREAD

**Issue by Irennnne** [Cartucho/vision_blender#23]
Hello,
My project aims to create dataset with the presence of surgical instruments. 
And I noticed that there is a surgical insrument in your sample video sequence. Is it real or virtual?
Could you share the sources of virtual surgical instruments or where I can get access to these instruments if it is virtual?
Thank you in advance.

Best,
Irene

**Comment by Cartucho** [comment]
I have discussed with @Irennnne that the surgical instruments are property of Intuitive Inc. and therefore I am not able to share them. Maybe there are other surgical instruments, besides the ones from Intuitive, whose CAD models are made available online?
