### ISSUE TITLE
key "ViewLayer" not found

### ISSUE THREAD

**Issue by nicola-hermann** [Cartucho/vision_blender#24]
![Screenshot (58)](https://user-images.githubusercontent.com/95233817/176397156-d396d5cb-d4be-4c77-893a-cfabff806cf0.png)

Blender version: 2.83.18

I think the changes from March 29th screwed up the data generation pipeline for Blender 2.83

**Comment by Cartucho** [comment]
I found that we could simply replace it with "bpy.context.view_layer", this way it is not name-dependent
