### ISSUE TITLE
BlenderNeuron + vision_blender design

### ISSUE THREAD

**Issue by imvetri** [Cartucho/vision_blender#3]
Hi,

Congratulations ! and thanks for sharing your work. 

I think vision_blender and BlenderNeuron have got great potential to work together. It is hard to communicate idea so I created this document to share. 

https://github.com/imvetri/artificial-intelligence/blob/master/Self.learning.neuron.model.md.

-Vetrivel.

**Comment by Cartucho** [comment]
Hi Vetrivel, what is the goal of your project?

**Comment by imvetri** [comment]
Hi @Cartucho. I want to see what happens if a camera feed is given to a neural network. The input to the camera is the neural network it feeds data.
