### ISSUE TITLE
Image depth

### ISSUE THREAD

**Issue by mingjunlovelybaby** [Cartucho/vision_blender#4]
This is a great job. I am trying to use a depth map, I want to know whether the depth map obtained by vision-blender is 8-bit or 16-bit

**Comment by Cartucho** [comment]
That's a great question, I used the Zmap directly out of the rendering so I am using the same as the default by blender.

I will look into it now and let you know.

**Comment by Cartucho** [comment]
It's `np.float64`.

Unlike depth cameras where usually you store in `uint16` and then you divide the value by `1000.0`, here you get directly the distance in meters (assuming that you have blender set to work with meters, which is the default).
![image](https://user-images.githubusercontent.com/15831541/101176967-236b3480-363f-11eb-98d8-e7d838dda275.png)

**Comment by mingjunlovelybaby** [comment]
Thank you very much for your quick reply. Your response will be of great help to me.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Cartucho <notifications@github.com>
发送时间: Friday, December 4, 2020 3:44:49 PM
收件人: Cartucho/vision_blender <vision_blender@noreply.github.com>
抄送: mingjunlovelybaby <sun834868349@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [Cartucho/vision_blender] Image depth (#4)


It's np.float64.

Unlike depth cameras where usually you store in uint16 and then you divide the value by 1000.0, here you get directly the distance in meters (assuming that you have blender set to work with meters, which is the default).
[image]<https://user-images.githubusercontent.com/15831541/101176967-236b3480-363f-11eb-98d8-e7d838dda275.png>

―
