### ISSUE TITLE
rosbag for rgbd

### ISSUE THREAD

**Issue by mingjunlovelybaby** [Cartucho/vision_blender#5]
Hi, I am currently working on rgbd cameras, and I noticed that you provided a python script to make rosbag for stereo. Have you tried to convert the image sequence of rgbd camera to rosbag, I don't know if it is feasible, do you have any ideas or suggestions. I am wondering if there is a problem with the rgbd data output by blender, which causes you not to provide rosbag for rgbd data

**Comment by Cartucho** [comment]
Hello, so what you are trying to do is to create a rosbag using the stereo images generated by the visionBlender addon?

**Comment by mingjunlovelybaby** [comment]
Thanks for your reply, I have solved the problem, this problem does not seem to be worth opening a issue.
