### ISSUE TITLE
I have the camera moving still no optical flow data is being captured.

### ISSUE THREAD

**Issue by vivasvan1** [Cartucho/vision_blender#6]
i am using blender 2.8

**Comment by vivasvan1** [comment]
My bad. Changed to cycles and it working.

**Comment by Cartucho** [comment]
Hello! Thank you for the feedback I will add a visual warning in the user interface mentioning that "Optical Flow" and "Segmentation masks" work only for Cycles!

**Comment by Cartucho** [comment]
Done, I added this warning:

![image](https://user-images.githubusercontent.com/15831541/103666075-0e4e3200-4f6c-11eb-919c-ec547589a693.png)
