### ISSUE TITLE
Why are there 4 channels in optical flow. and what do they mean?

### ISSUE THREAD

**Issue by vivasvan1** [Cartucho/vision_blender#7]
Channel 0 - ?
Channel 1 - ?
Channel 2 - ?
Channel 3 - Alpha

**Comment by vivasvan1** [comment]
flow should only have 2 channels if I am correct

**Comment by Cartucho** [comment]
Hello, that's a very good question, I am simply saving the output of vector since in their documentation they say it is optical flow.

I do not know the answer but I will look into it.

**Comment by Cartucho** [comment]
According to the documentation, [link here](https://docs.blender.org/manual/en/latest/render/layers/passes.html), two of them are the motion to the previous frame and the other two are to the next frame.

![image](https://user-images.githubusercontent.com/15831541/103663790-69325a00-4f69-11eb-9b36-dfc7b1de288c.png)

**Comment by Cartucho** [comment]
@vivasvan1 could you please confirm that it worked?

**Comment by Cartucho** [comment]
@vivasvan1 I have fixed the optical flow and I added an example to the samples:

![image](https://user-images.githubusercontent.com/15831541/117145264-e1d7e480-adaa-11eb-9d70-f7769fcdaa1e.png)

Now you only get 2 channels, representing the ∆x (channel 0) and ∆y (channel 1), from the current to the next frame.

**Comment by phongnhhn92** [comment]
> Do you think you could give it a try to figure out which is which?
> 
> I think that `channel 0` and `channel 1` are the motion to the next frame. `Channel 0` should should be in the `x` direction and `channel 1` in the y direction.
> 
> Let me know if you can give it a try, otherwise I will investigate further and let you know.

Hi @Cartucho, I am a bit confused on how you have put negative in the 0-channel ? Is this because of blender coordinate system ? 

I am trying to get the backward flow (from current to the previous frame). Can u elaborate on how to do that ?

**Comment by Cartucho** [comment]
Hi, that discussion was during the development phase.

Have a look into the sample code:

https://github.com/Cartucho/vision_blender/blob/c3dbf61d279213ea73e41bdc618efd9b84f0b0b5/samples/read_data.py#L63-L65

The optical flow displaces from time `t` to time `t+1`.

Therefore, if you want backward flow, then get the optical flow of the previous frame and invert it. 
Time `t+1` pt_t+1 = (u, v), then at time `t` pt_t =  (u - int(round(flow_tmp[0])), v - int(round(flow_tmp[1]))),
where `flow_tmp` is the optical flow at time `t`.

Think about it, you only need to use the optical flow of the previous frame (starting from frame 1, above) and invert the vector.
