### ISSUE TITLE
Ground Truth

### ISSUE THREAD

**Issue by mingjunlovelybaby** [Cartucho/vision_blender#8]
hi, do you know how to generate the ground truth.

**Comment by Cartucho** [comment]
Hi, you can find these instructions in the README file. Basically, you have to install the add-on and then using the user interface select which ground truth you want to generate.

**Comment by mingjunlovelybaby** [comment]
Thank u. I got this. 

When I was reading your Paper, I found that you mentioned that using cycles will produce distortion (the depth value needs to be converted). It seems that the latest version of Blender has been fixed, so the 
def correct_cycles_depth is no longer needed in the Programm.

**Comment by Cartucho** [comment]
Oh really? I will give it a try, which version are you talking about? 2.9? I haven't tried that yet

**Comment by mingjunlovelybaby** [comment]
yes. 2.91.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Cartucho ***@***.***>
发送时间: Sunday, April 11, 2021 11:06:28 AM
收件人: Cartucho/vision_blender ***@***.***>
抄送: mingjunlovelybaby ***@***.***>; Author ***@***.***>
主题: Re: [Cartucho/vision_blender] Ground Truth (#8)


Oh really? I will give it a try, which version are you talking about? 2.9? I haven't tried that yet

―
